models:
  small_model: qwen2.5-3b-instruct
  large_model: gpt-4o
  router_model: gemini-2.5-flash-thinking
  enable_threshold: false
  threshold: 4
  use_local_router: false
  local_router_model: meta-llama/llama-3.2-3b-instruct:free
api:
  small_key_path: usage/qwen
  large_key_path: usage/bianxie1
  router_key_path: usage/bianxie1
  small_api_base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  large_api_base_url: https://api.bianxie.ai/v1
  router_api_base_url: https://api.bianxie.ai/v1
  local_router_base_url: https://openrouter.ai/api/v1
timeout: 300
system:
  prompt_path: prompt/generate_prompt.txt
  compare_prompt_path: prompt/direct_solve_prompt.txt
  workers: 10
  enable_judge: true
  gold_answer: '16'
query: Define all possible orientations and placements of the L-shaped tile within
  the 2x5 rectangle.
dataset:
  enabled: true
  path: dataset/TestData/s1k_testPerformance.json
  limit: 30
  output_dir: model_compare_results/
  build:
    enabled: false
    use_models_for_execution: false
    use_ground_truth_to_guide_planner: false
    save_thinking: true
evaluation:
  enabled: true
  planner_enabled: true
  executor_enabled: true
  model: deepseek-chat
  key_path: usage/deepseek2
  api_base_url: https://api.deepseek.com
