# 模型配置
models:
  small_model: "qwen/qwen-2.5-7b-instruct" # meta-llama/llama-3.1-8b-instruct, qwen/qwen-2.5-7b-instruct, deepseek/deepseek-r1-0528-qwen3-8b
  large_model: "openai/gpt-4o" # meta-llama/llama-3.3-70b-instruct, deepseek/deepseek-r1-0528, anthropic/claude-3.5-sonnet, google/gemini-2.5-flash
  router_model: "qwen/qwen-2.5-7b-instruct" # anthropic/claude-sonnet-4, openai/gpt-4o, qwen/qwen3-235b-a22b
  threshold: 3
  local_threshold: 5  # 难度阈值，大于等于此值时使用大模型
  use_local_router: false  # 是否使用本地部署的路由模型
  local_router_model: "saves/Qwen3-1.7B-Instruct/full/sft"  # 本地模型路径

# API配置
api:
  key_path: "usage/openrouter1"
  key_path1: "usage/openrouter"
  key_path2: "usage/openrouter2"
  key_path3: "usage/openrouter3"
  base_url: "https://openrouter.ai/api/v1"
  small_api_base_url: "https://openrouter.ai/api/v1"  # 小模型API基础URL
  large_base_url: "https://openrouter.ai/api/v1"  # 大模型API基础URL
  router_base_url: "https://openrouter.ai/api/v1"  # 路由模型API基础URL
  local_router_base_url: "http://127.0.0.1:8000/v1"  # 本地部署的路由模型API基础URL
  # key_path: "usage/together"
  # base_url: "https://api.together.xyz/v1"

# 系统配置
system:
  prompt_path: "prompt/generate_prompt.txt"
  compare_prompt_path: "prompt/direct_solve_prompt.txt"
  workers: 10  # 并行工作线程数
  enable_judge: True  # 是否启用答案正确性判断
  gold_answer: "180"  # 标准答案，如果启用判断则必填
# 查询配置
# query: "Find the last three digits of the product of the positive roots of $\\sqrt{1995}x^{\\log_{1995}x}=x^2.$"
# query: "What is the result of 1+1?"
query: "3. (6 points) A construction company was building a tunnel. When $\\frac{1}{3}$\\ of the tunnel was completed at the original speed, they started using new equipment, which increased the construction speed by $20 \\%$ and reduced the working hours to $80 \\%$ of the original. As a result, it took a total of 185 days to complete the tunnel. If they had not used the new equipment and continued at the original speed, it would have taken $\\qquad$ days to complete the tunnel."  

dataset:
  enabled: true  # 是否启用数据集
  path: "dataset/original_data/math200.json"
  limit: 1
  output_dir: "model_compare_results/"
